### ISSUE TITLE
[META] Version 5 checklist

### ISSUE THREAD

**Issue by timgws** [Chumper/Datatable#335]
This is a meta bug to show the current state of work for Version 5.

# New Features
- [ ] #333 - **Version 1.10 needs to be treated as a first class citizen**
- [ ] #332 - **CollectionEngine does not support sorting by multiple columns at the same time**
- [ ] #334 - **'CustomEngine', an event based engine for searching**

# Bug/Feature fixes
- [ ] #308 - **Properly allow mocking Laravel for unit tests.**

**Comment by Chumper** [comment]
Hey @timgws, i could not find an email, so i just write a comment.
I have created a new branch `datatable3` where i want to rewrite the plugin for laravel 5.
I would like to invite you all to participate and discuss. A few ideas i already outlined there but there is definitely more stuff to discuss.

I also want to properly document every aspect of the plugin wherever possible, e.g. on an own page.

As you already did an awesome job on taking over the development i would be happy to have you on board for the new version.

Let me know what you think.

**Comment by Javier-Rotelli** [comment]
hi @Chumper are you aiming for a complete rewrite?
I'm using this plugin on laravel 5 and it works great, it has bugs, but it mostly works. 
I really like the idea of it having good documentation.

**Comment by Chumper** [comment]
@Javier-Rotelli In most parts yes, but i am open to pull in already written code if it fits.

I want to clearly separate the three parts which are currently mixed together:
- Column configuration
- Request handling
- Data processing

The current version was built with that in mind but as bugs came in I did not focus on that too much.
@timgws already started to work on some core components for a newer version and I would like to keep some of them in as he has the same idea in mind.
